server:
  port: 7901
user:
  userservicepath: http://localhost:7900/user/
eureka:
  client:
    serviceUrl:
      defaultZone: http://ljy:123456@localhost:8761/eureka
  instance:
    prefer-ip-address: true
spring:
  application:
    name: service-consumer-movie