server:
  port: 7901
eureka:
  client:
    serviceUrl:
      defaultZone: http://ljy:123456@localhost:8761/eureka
  instance:
    prefer-ip-address: true
spring:
  application:
    name: service-consumer-movie-feign-with-hystrix

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
  hystrix:
    enabled: true
