spring:
  application:
    name: eureka-server

security:
  basic:
    enabled: true
  user:
    password: 123456
    name: ljy

---
spring:
  profiles: peer1

server:
  port: 8761

eureka:
  instance:
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://ljy:123456@ljyserver2:8762/eureka


---
spring:
  profiles: peer2

server:
  port: 8762

eureka:
  instance:
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://ljy:123456@ljyserver1:8761/eureka