spring:
  application:
    name: spring-config-server-eureka

  cloud:
    config:
      server:
        git:
          uri: https://github.com/lijunyi01/SpringCloudLearn.git
          search-paths: modules/springcloudlearn-parent/config-repo/

eureka:
  client:
    serviceUrl:
      defaultZone: http://ljy:123456@ljyserver1:8761/eureka,http://ljy:123456@ljyserver2:8762/eureka

security:
  basic:
    enabled: true
  user:
    password: 123456
    name: ljy

---
spring:
  profiles: peer1

server:
  port: 9071


---
spring:
  profiles: peer2

server:
  port: 9072