server:
  port: 8080

spring:
  application:
    name: springconfigserver

  cloud:
    config:
      server:
        git:
          uri: https://github.com/lijunyi01/SpringCloudLearn.git
          search-paths: modules/springcloudlearn-parent/spring-config-server/config-repo/


