server:
  port: 8888

spring:
  application:
    name: spring-config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/lijunyi01/spring-cloud-config-repo.git


