spring:
  application:
    name: service-hystrix-turbine

server:
  port: 8031

eureka:
  client:
    serviceUrl:
      defaultZone: http://ljy:123456@localhost:8761/eureka

turbine:
  aggregator:
    cluster-config: CUSTOMERS
  app-config:



