server:
  port: 8040

eureka:
  client:
    service-url:
      defaultZone: http://ljy:123456@localhost:8761/eureka
  instance:
    prefer-ip-address: true

spring:
  application:
    name: service-gateway-zuul

zuul:
  ignore-services: '*'
  sensitive-headers: Cookie,Set-Cookie,Authorization
  routes:
    service-provider-user: spuser/**
